import Link from "next/link"
import { ArrowLeft, BarChart, PieChart, LineChart, Download } from "lucide-react"

export default function ReportsPage() {
  return (
    <div className="container mx-auto py-10">
      <div className="flex items-center mb-8">
        <Link href="/dashboard" className="text-foreground opacity-60 hover:text-primary mr-4">
          <ArrowLeft size={20} />
        </Link>
        <div>
          <h1 className="text-3xl font-bold text-foreground">Reports</h1>
          <p className="text-foreground opacity-60">View and generate reports for your organization</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-8">
        <div className="card-modern">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-medium text-foreground">Employee Reports</h2>
            <BarChart className="h-5 w-5 text-primary" />
          </div>
          <p className="text-sm text-foreground opacity-60 mb-4">
            Generate reports on employee data, demographics, and statistics.
          </p>
          <Link href="/dashboard/reports/employees" className="text-primary hover:text-primary-dark text-sm">
            View Reports
          </Link>
        </div>

        <div className="card-modern">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-medium text-foreground">Onboarding Reports</h2>
            <PieChart className="h-5 w-5 text-secondary" />
          </div>
          <p className="text-sm text-foreground opacity-60 mb-4">
            Generate reports on onboarding processes, completion rates, and feedback.
          </p>
          <Link href="/dashboard/reports/onboarding" className="text-primary hover:text-primary-dark text-sm">
            View Reports
          </Link>
        </div>

        <div className="card-modern">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-medium text-foreground">Compliance Reports</h2>
            <LineChart className="h-5 w-5 text-primary" />
          </div>
          <p className="text-sm text-foreground opacity-60 mb-4">
            Generate reports on compliance status, document expiration, and audits.
          </p>
          <Link href="/dashboard/reports/compliance" className="text-primary hover:text-primary-dark text-sm">
            View Reports
          </Link>
        </div>
      </div>

      <div className="card-modern">
        <h2 className="text-xl font-bold mb-6 text-foreground">Recent Reports</h2>
        <div className="overflow-x-auto">
          <table className="w-full border-collapse">
            <thead>
              <tr className="border-b border-border">
                <th className="px-4 py-3 text-left text-sm font-medium text-foreground opacity-60">Report Name</th>
                <th className="px-4 py-3 text-left text-sm font-medium text-foreground opacity-60">Type</th>
                <th className="px-4 py-3 text-left text-sm font-medium text-foreground opacity-60">Generated</th>
                <th className="px-4 py-3 text-left text-sm font-medium text-foreground opacity-60">Generated By</th>
                <th className="px-4 py-3 text-right text-sm font-medium text-foreground opacity-60">Actions</th>
              </tr>
            </thead>
            <tbody>
              {[
                {
                  name: "Employee Headcount Q2 2023",
                  type: "Employee",
                  date: "Jun 10, 2023",
                  user: "John Doe",
                },
                {
                  name: "Onboarding Completion Rate",
                  type: "Onboarding",
                  date: "Jun 8, 2023",
                  user: "Jane Smith",
                },
                {
                  name: "Document Expiration Summary",
                  type: "Compliance",
                  date: "Jun 5, 2023",
                  user: "John Doe",
                },
                {
                  name: "Department Distribution",
                  type: "Employee",
                  date: "Jun 1, 2023",
                  user: "Jane Smith",
                },
                {
                  name: "Onboarding Feedback Summary",
                  type: "Onboarding",
                  date: "May 28, 2023",
                  user: "John Doe",
                },
              ].map((report, index) => (
                <tr key={index} className="border-b border-border hover:bg-card">
                  <td className="px-4 py-4 text-sm text-foreground">{report.name}</td>
                  <td className="px-4 py-4 text-sm text-foreground">{report.type}</td>
                  <td className="px-4 py-4 text-sm text-foreground">{report.date}</td>
                  <td className="px-4 py-4 text-sm text-foreground">{report.user}</td>
                  <td className="px-4 py-4 text-sm text-right">
                    <button className="text-primary hover:text-primary-dark">
                      <Download size={16} />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}
